Per Instance Underglow Behavior data. New "zmk_apa_led_strip" device
Warning: this commit compiles correctly, but the linker returns
         undefined reference to `__device_dts_ord_26'
         undefined reference to `__device_dts_ord_28'

In this commit I have re-defined all the data variables used by the
undergow behavior so that there is a separate set of variables
for each instance of the behavior.

I have also introduced a new device definition: zmk_apa_led_strip
in file app/drivers/led_strip/apa.c which represents an All
Points Addressable Led Strip Device which is implemented upon
the previous led_strip device.
Each zmk_apa_led_strip instance inludes a number of "subsets"
devices zmk_apa_led_strip_subs defined in file
app/drivers/led_strip/apa_subs.c, each of which represents
a subset inluding specific "points" of the whole led strip,
and which is referenced from the underglow behaviors.
An axample of how the new underglow behaviors and devices
are defined is given if file app/boards/arm/bt60/bt60.dts

In this commit I tried to implement the suggestions given
by @petejohanson in the comments he left on my previous
commit:
https://github.com/cirolandolfi/zmk/commit/aa71369b0f2c699df350d64f871504af3e544d7b#comments

Regarding the linker errors:
It appears that the code sections from the new files apa.c
and apa_subs.c are discarded by the linker.
The files appear to be correctly compiled, and the apa.c.obj
and apa_subs.c.obj are present in the directory
app.dir/drivers/led_strip. However, any global variable
defined in those files, even if referenced from other files,
appear discarded by the linker, as can be seen in the
app/build/zephyr/zephyr_prebuilt.map file.